### ISSUE TITLE
Automate the contributor licence agreement process

### ISSUE THREAD

**Issue by codedemonuk** [trainline/environment-manager#1]
Having a requirement for a signed CLA is a slow and laborious process, and imposes a financial cost upon the contributor to post a piece of dead tree to London.

Instead, you could use [CLAHub](https://www.clahub.com/) to automate this and better integrate with GitHub.

**Comment by duncanhall** [comment]
Thanks @codedemonuk - we're leaving this "as-is" for now as the barrier-to-contributing is still sufficiently low (open a Pull Request that contains just a copy of the CLA under `<Your Name>.txt` in the `contributors` directory. No trees need harming!
