### ISSUE TITLE
Rational of semantic versionning limitation on package versions

### ISSUE THREAD

**Issue by paulRbr** [trainline/environment-manager#168]
Hello,
Is there a rational to limit package versions with semantic versioning? 

https://github.com/trainline/environment-manager/blob/master/server/api/swagger.yaml#L3139

For backend applications that gets deployed multiple times a day I believe semantic versioning is not useful for package versions. Usually the SHA1 of a commit is enough to identify a package / deploy version.

What do you think?

**Comment by duncanhall** [comment]
Other than being a widely accepted standard, the use of semver enables comparison of software versions across environments. 

It is easy to make statements about the "latest version" when comparing:

 _version 1.2.0 in staging and version 1.1.4 in production_. 

The same is not true when comparing:

 _aad4fe7a in staging and version ef7c78ba in production_ 

Additionally, if you want to include commit info in your semantic version, [semver supports this](http://semver.org/#spec-item-10).
