### ISSUE TITLE
Fail on Launch Configuration creation when SG is not found

### ISSUE THREAD

**Issue by mvisonneau** [trainline/environment-manager#277]
For the moment, when specified security groups in deployment maps are not found in the VPC, it does not prevent the deployment from failure. This behavior should be changed to failing.

```
[14:05:11.16] Security group "sg-0000000" not found in "vpc-0000000" VPC. It is assigned because specified in the server role configuration.
```

**Comment by DavidIHunt** [comment]
This will be fixed by PR 286 https://github.com/trainline/environment-manager/pull/286
