### ISSUE TITLE
Allow the use of SG ids in deployment maps configuration

### ISSUE THREAD

**Issue by mvisonneau** [trainline/environment-manager#278]
We cannot assign a specific security group id into deployment maps. It has to be defined by the name of the SG. It would be great if we could also specify it by its id. For the moment it just fails to lookup the security group if the id is specified.

**Comment by ChrisTurvil** [comment]
Won't fix. If we use IDs, it will tie the Deployment Map to a particular Environment Type. Names ensure the map remains portable across VPCs. Thanks, Chris.
