### ISSUE TITLE
Deployment logs have an incorrect content type in response header

### ISSUE THREAD

**Issue by codedemonuk** [trainline/environment-manager#39]
When viewing the deployment logs, the content type specified in the HTML header is `text/html` which results in the log file looking like unformatted html in quierks mode; it is unlikely that the log file returned would be a valid HTML file.

The content type should be `text/plain` because logs are plain text and it would also mean that browsers would show the log in a monospaced font instead.

**Comment by filso** [comment]
Thanks, I'll take a look at this

**Comment by mvisonneau** [comment]
When do you think this will be implemented?

**Comment by duncanhall** [comment]
@codedemonuk @mvisonneau This is now fixed via https://github.com/trainline/environment-manager/pull/178

**Comment by mvisonneau** [comment]
👍
