### ISSUE TITLE
nugetTest.js requires you to be actually inside TTL firewall

### ISSUE THREAD

**Issue by Takaloy** [trainline/environment-manager#7]
https://github.com/trainline/environment-manager/blob/7cea47b629a8ea813f7e26818ae5a90d148b2b6b/server/test/modules/dm-packer/nugetTest.js#L27

**Comment by duncanhall** [comment]
Hi @Takaloy, thanks for your input.

The tests in `server/test` directory are unit tests and therefore should not have any network expectations. The specific test you pointed to is designed to test `getDownloadLink()` method, which simply parses an XML response and returns an http link (or Errors if it's not found).

Nothing in this test has any network or firewall dependencies.
